apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: rkim
  labels:
    app: db
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 20
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: db-secret
        name: db-deployment
        image: harbor.dev.afsmtddso.com/rk-harbor-project/db@sha256:3449edabddfc8c014baafe9733be19551dd2f0a63e94db4f3397f64c0405a32e
        ports:
        - containerPort: 5432
